[profile.default]
src = 'src'
test = 'test'
script = 'script'
out = 'out'
libs = ['lib']
cache_path = 'cache'
solc = "0.8.30"
via_ir = true
optimizer = true
optimizer_runs = 200

# For dependencies
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    'forge-std/=lib/forge-std/src/',
    '@fws-payments/=lib/fws-payments/src/',
    '@pdp/=lib/pdp/src/',
    '@session-key-registry/=lib/session-key-registry/src/',
    '@pythnetwork/pyth-sdk-solidity/=lib/pdp/lib/pyth-sdk-solidity/',
]

# Allow reading test data files
fs_permissions = [{ access = "read", path = "./test" }]

[lint]
exclude_lints = [
    "asm-keccak256",
    "mixed-case-function",
    "mixed-case-variable",
    "pascal-case-struct",
    "screaming-snake-case-immutable",
]
